name: mamapola_app_v1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.0
  flutter_dotenv: ^5.2.1
  flutter_form_builder: ^10.0.1
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  form_builder_validators: ^11.1.2
  image_picker: ^1.1.2
  flutter_native_splash: ^2.4.2
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  equatable: ^2.0.7
  dropdown_button2: ^2.3.9
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  bitsdojo_window: ^0.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  fl_chart: ^1.0.0
  path_provider: ^2.1.4
  open_file: ^3.3.2
  app_links: ^3.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/logo1.png # Incluido explícitamente para claridad
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo1.png
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center